const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
app.disableHardwareAcceleration();
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-renderer-')));
let saved = [], finish = [], choice = 'cancel', saveMode = 'success';
ipcMain.handle('test:open', () => null);
ipcMain.handle('test:link', (_event, url) => ({ path: 'F:\\docs\\linked.md', key: 'linked', baseUrl: 'file:///F:/docs/', content: '# Linked' }));
ipcMain.handle('test:external', () => true);
ipcMain.handle('test:confirm', () => choice);
ipcMain.handle('test:save', (_event, data) => { saved.push(data); if (saveMode === 'cancel') return null; if (saveMode === 'error') return { error: 'Test write failure' }; return { path: data.filePath || 'F:\\docs\\saved.md', key: data.filePath || 'saved', baseUrl: 'file:///F:/docs/', content: data.content }; });
ipcMain.handle('test:finish', (_event, ready) => { finish.push(ready); return true; });
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1280, height: 820, webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true, offscreen: true, backgroundThrottling: false, partition: `test-${Date.now()}` } });
  const errors = [];
  win.webContents.on('console-message', (_event, level, message) => { if (level >= 3) errors.push(message); });
  try {
    await win.loadFile(path.join(__dirname, '../renderer/index.html'));
    const results = await win.webContents.executeJavaScript(`(async () => {
      const results = [];
      function check(value, message) { if (!value) throw new Error(message); results.push(message); }
      const tick = () => new Promise(resolve => setTimeout(resolve, 80));
      const source = '# Heading\\n\\nrepeat **repeat** and [repeat](https://example.com/repeat) &amp; <em>raw</em>\\n\\n> quoted **words**\\n\\n| First | Second |\\n|---|---|\\n| alpha | beta |\\n\\n\`\`\`js\\nconst js = 1;\\n\`\`\`\\n\\n![picture](images/a.png)\\n';
      openDocument({ path: 'F:\\\\docs\\\\one.md', key: 'one', content: source, baseUrl: 'file:///F:/docs/' });
      await tick();
      check(preview.querySelector('strong').textContent === 'repeat', 'Markdown formatting survives mapping');
      check(preview.querySelector('code').textContent.includes('const js = 1;'), 'Code block renders as code');
      check(preview.querySelector('img').getAttribute('src') === 'file:///F:/docs/images/a.png', 'Relative image resolved from document');
      const boldLeaf = preview.querySelector('strong span');
      check(boldLeaf.sourcePositions[0].start === source.indexOf('**repeat**') + 2, 'Repeated word maps to correct occurrence');
      const linkLeaf = preview.querySelector('a span');
      check(linkLeaf.sourcePositions[0].start === source.indexOf('[repeat]') + 1, 'Link label maps without URL');
      const quoted = [...preview.querySelectorAll('strong span')].find(node => node.textContent === 'words');
      check(quoted.sourcePositions[0].start === source.indexOf('**words**') + 2, 'Blockquote inline positions');
      const beta = [...preview.querySelectorAll('td span')].find(node => node.textContent === 'beta');
      check(beta.sourcePositions[0].start === source.indexOf('beta'), 'Table cell positions');
      const code = preview.querySelector('code span');
      check(code.sourcePositions[0].start === source.indexOf('const js'), 'Code positions exclude language fence');
      editor.focus(); editor.setSelectionRange(source.indexOf('**repeat**') + 2, source.indexOf('**repeat**') + 8); highlightSourceSelection();
      check(CSS.highlights.get('source-selection')?.size === 1, 'Source selection highlights preview range');
      editor.blur(); const range = document.createRange(); range.setStart(linkLeaf.firstChild, 1); range.setEnd(linkLeaf.firstChild, 4); document.getSelection().removeAllRanges(); document.getSelection().addRange(range); document.dispatchEvent(new Event('selectionchange'));
      check(mirroredSelection.start === source.indexOf('[repeat]') + 2 && mirroredSelection.end === source.indexOf('[repeat]') + 5, 'Preview selection highlights exact source offsets');
      check(document.activeElement !== editor && !document.getSelection().isCollapsed, 'Reverse highlight preserves preview selection and focus');
      const count = tabs.length; openDocument({ path: 'F:\\\\docs\\\\one.md', key: 'one', content: 'wrong' }); check(tabs.length === count && editor.value === source, 'Duplicate open preserves active document');
      setMode('preview-only'); const before = editor.value; document.dispatchEvent(new KeyboardEvent('keydown', { key: 'b', ctrlKey: true, bubbles: true })); check(editor.value === before, 'Preview hotkey cannot change hidden source');
      setMode('split'); editor.focus(); editor.setSelectionRange(0, 0); actions.bold(); check(editor.value.startsWith('**bold text**'), 'Toolbar insertion'); undo(); check(editor.value === source && !dirty(current()), 'Undo returns to saved baseline');
      $('find-input').value = 'repeat'; updateSearch(false); check(matches.length === 4, 'Find counts Markdown occurrences');
      $('replace-input').value = 'changed'; $('replace-all').click(); check(!editor.value.includes('repeat'), 'Replace all'); undo(); check(editor.value === source, 'Replace all is one undo step');
      editor.value = Array.from({length: 120}, (_, i) => 'Paragraph ' + i + '\\n').join('\\n'); changed(); render(); await tick();
      preview.firstElementChild.style.height = '600px'; scrollAnchors = null;
      editor.scrollTop = sourceY(blocks[30].start); syncScroll(editor);
      check(Math.abs(preview.scrollTop - previewY(blocks[30])) < 3, 'Scroll follows source block despite unequal block heights');
      await tick(); $('sync-scroll').checked = false; const frozen = preview.scrollTop; editor.scrollTop += 100; syncScroll(editor);
      check(preview.scrollTop === frozen, 'Scroll sync can be disabled'); $('sync-scroll').checked = true;
      setSplit(30); await tick(); check(Math.abs($('editor-shell').offsetWidth / (workspace.clientWidth - 6) - .3) < .02, 'Divider resizes the editor'); setSplit(50);
      render(); await tick();
      editor.scrollTop = 500; editor.setSelectionRange(80, 90); remember(); const originalId = currentTabId; newTab(); switchTab(originalId); await tick();
      check(editor.scrollTop > 450 && editor.selectionStart === 80 && editor.selectionEnd === 90, 'Tab restores scroll and selection');
      persist(); const session = JSON.parse(localStorage.getItem('md-session-v1')); check(session.tabs.some(tab => tab.content.includes('Paragraph 119')), 'Recovery snapshot contains unsaved draft');
      const html = '<img src=x onerror="window.pwned=true"><script>window.pwned=true<\\/script>'; editor.value = html; changed(); render(); check(!preview.querySelector('script') && !preview.querySelector('[onerror]'), 'Mapped preview remains sanitized');
      await saveTab(current()); check(!dirty(current()), 'Successful save updates baseline');
      return results;
    })()`);
    console.log(results.map(value => 'PASS ' + value).join('\n'));
    await win.webContents.executeJavaScript(`
      openDocument({path: 'F:\\\\docs\\\\review.md', key: 'review', baseUrl: 'file:///F:/docs/', content: '# Linked selection\\n\\nSelect **the same words** in either pane.\\n\\n## Source and preview\\n\\n- Exact text highlighting\\n- Session recovery\\n- Find and replace\\n\\n| Feature | Status |\\n|---|---|\\n| Linked selection | Ready |\\n| Document outline | Ready |\\n\\n> Keep your place when switching tabs.\\n'});
      setMode('split'); $('searchbar').hidden = true; $('outline').hidden = false; editor.focus();
      editor.setSelectionRange(editor.value.indexOf('the same words'), editor.value.indexOf('the same words') + 14); highlightSourceSelection();
    `);
    await new Promise(resolve => setTimeout(resolve, 200));
    const screenshot = await win.webContents.capturePage();
    fs.mkdirSync(path.join(__dirname, '.artifacts'), { recursive: true });
    fs.writeFileSync(path.join(__dirname, '.artifacts/split.png'), screenshot.toPNG());
    const drag = await win.webContents.executeJavaScript(`(() => { const rect = preview.querySelector('strong').getBoundingClientRect(); return { x: Math.round(rect.left + 1), y: Math.round(rect.top + rect.height / 2), end: Math.round(rect.right - 1) }; })()`);
    win.webContents.sendInputEvent({ type: 'mouseDown', x: drag.x, y: drag.y, button: 'left', clickCount: 1 });
    win.webContents.sendInputEvent({ type: 'mouseMove', x: drag.end, y: drag.y, modifiers: ['leftButtonDown'] });
    win.webContents.sendInputEvent({ type: 'mouseUp', x: drag.end, y: drag.y, button: 'left', clickCount: 1 });
    await new Promise(resolve => setTimeout(resolve, 100));
    if (!await win.webContents.executeJavaScript(`!!mirroredSelection && backdrop.querySelector('mark')?.textContent === 'the same words' && document.activeElement !== editor`)) throw new Error('Mouse drag did not mirror selection');
    console.log('PASS real mouse drag mirrors preview selection');
    fs.writeFileSync(path.join(__dirname, '.artifacts/reverse.png'), (await win.webContents.capturePage()).toPNG());
    await win.webContents.executeJavaScript(`editor.value += '\\nUnsaved recovery check'; changed(); persist();`);
    const reload = () => new Promise(resolve => { win.webContents.once('did-finish-load', resolve); win.webContents.reload(); });
    await reload();
    const recovered = await win.webContents.executeJavaScript(`editor.value.includes('Unsaved recovery check') && dirty(current())`);
    if (!recovered) throw new Error('Session reload failed');
    console.log('PASS unsaved session restores after reload');
    async function requestClose(expected, message) {
      const count = finish.length; win.webContents.send('test:request-close');
      for (let i = 0; finish.length === count && i < 50; i++) await new Promise(resolve => setTimeout(resolve, 20));
      if (finish.length === count || finish.at(-1) !== expected) throw new Error(message);
      console.log('PASS ' + message);
    }
    choice = 'cancel'; await requestClose(false, 'Cancel keeps window open');
    choice = 'save'; saveMode = 'cancel'; await requestClose(false, 'Cancel Save as keeps drafts');
    saveMode = 'error'; await requestClose(false, 'Write error prevents close');
    if (!await win.webContents.executeJavaScript(`dirty(current()) && !editor.readOnly && $('notice-text').textContent.includes('Test write failure')`)) throw new Error('Failed save lost draft or hid error');
    saveMode = 'success'; await requestClose(true, 'Save all completes before close');
    await reload();
    await win.webContents.executeJavaScript(`editor.value += '\\nDiscard this'; changed();`);
    choice = 'discard'; await requestClose(true, 'Discard closes without saving');
    await reload();
    if (!await win.webContents.executeJavaScript(`!editor.value.includes('Discard this') && !dirty(current())`)) throw new Error('Discarded draft was resurrected');
    await requestClose(true, 'Clean close handshake');
    if (errors.filter(message => !message.includes('ERR_FILE_NOT_FOUND')).length) throw new Error(errors.join('\n'));
    console.log('PASS close handshake; saved snapshots: ' + saved.length);
    win.destroy(); app.exit(0);
  } catch (error) { console.error(error.stack); win.destroy(); app.exit(1); }
});
